apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'myapp-arocd-demo'
  namespace: 'argocd'
spec:
  project: 'default'
  destination:  
    namespace: 'myapp'
    server: 'https://kubernetes.default.svc'
  source:
    path: '.'
    repoURL: 'https://github.com/AdyaPatil/Demo_Python.git'
    targetRevision: 'HEAD'
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
